name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  plugin_test_latest:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: 'zigmod version'
  plugin_test_oldest:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          # https://github.com/kachick/asdf-zigmod/blob/8a7095692e6a880568a5b48c441ea518ef6a61cb/bin/download#L12
          # https://github.com/kachick/asdf-zigmod/blob/8a7095692e6a880568a5b48c441ea518ef6a61cb/lib/utils.bash#L59-L61
          version: 'UPDATE ME!'
          command: 'zigmod version'
