name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  plugin_test_latest:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: 'zigmod version'
  plugin_test_oldest:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          # v8 is the first turning point of the assets naming. See comments in function of download_release() for further detail.
          version: 'v8-1993719'
          command: 'zigmod version'
  plugin_test_latest_for_aarch64:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite_arm64:latest
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: 'zigmod version'
