name: dprint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dprint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
