name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/setup@v2
      - run: 'asdf plugin-add yamlfmt .'
      - uses: asdf-vm/actions/install@v2
      - run: makers lint
