name: mise
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  plugin-test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14 # M1
          - macos-13 # Intel
        target:
          - command: mise x zigmod@latest -- zigmod version
          # Having newer "r" prefix instead of older "v", but not the latest(r89 or newer)
          - command: mise x zigmod@r88 -- zigmod version
          # Supporting oldest
          - command: mise x zigmod@r75 -- zigmod version
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@3bc85396a273ed82bba5e53a15174bbf9dba095c # v2.0.2
        with:
          install: false
          # Enabling plugin cache in mise-action made many problems, should be avoided
          # https://github.com/kachick/asdf-cargo-make/pull/77
          # https://github.com/jdx/rtx-action/issues/211
          # https://github.com/kachick/asdf-zigmod/pull/138/commits/e47254c4d99a2f13d4265522290bbec12c3466cb
          cache: false
      - name: Setup mise
        run: |
          if [ '${{ github.event_name }}' = 'pull_request' ]; then
            mise plugins install --force zigmod 'https://github.com/${{ github.repository }}.git#${{ github.event.pull_request.head.sha }}'
          else
            mise plugins install --force zigmod 'https://github.com/${{ github.repository }}.git#${{ github.sha }}'
          fi
      - name: Test
        run: |
          ${{ matrix.target.command }}
