name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  latest:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: 'zigmod version'
  oldest_for_testing_subcommand:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          version: 'v51'
          # `version` subcommand exists since v51 https://github.com/nektro/zigmod/commit/ef20897b8196b4f3da3ee9bcc5ab731851d3aa2b
          command: 'zigmod version'
  oldest_for_assets_naming:
    timeout-minutes: 10
    # v21 does not pass tests only in MacOS. `Abort trap: 6           "$@"`
    runs-on: ubuntu-latest
    steps:
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          # See comments in function of download_release() for further detail.
          version: 'v21'
          # `version` subcommand exists since v51 https://github.com/nektro/zigmod/commit/ef20897b8196b4f3da3ee9bcc5ab731851d3aa2b
          command: 'zigmod'
  latest_for_aarch64:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: raspios_lite_arm64:latest
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: 'zigmod version'
